- dist/fetch_collectors.sh
> Avoid fetching the collector packages on every build

- README.md
- api/rest/rest.go
- collector_sidecar.yml
- collector_sidecar_windows.yml
- context/context.go
The default URI for the Graylog REST API changed to http://127.0.0.1:9000/api/
> Update server_url defaults for Graylog 2.1.x

- common/fs.go
This makes sure that the walk will be continued and not aborted on the first error.
> Return filepath.SkipDir in case of an error during file walk

- Makefile
- common/logger_unix.go
- services/control_handler_unix.go
This makes the sidecar build on the solaris/amd64 platform. We **don't** provide any official support though.
Tested on omnios/r151016.
> Add build support for solaris/amd64 (Solaris/Illumos/OmniOS)

- api/graylog.go
- api/rest/rest.go
- benchmarks/bench-rest-api.go
- services/periodicals.go
Previously we created a new transport connection for every HTTP request.
> Use a shared HTTP client/transport to ensure persistent connections

- api/graylog.go
API response changed from GL 2.1 > 2.2. Empty response vs. back channel with runtime configuration updates.
> Fix backwards compatibility

- README.md
- backends/nxlog/nxlog.go
- cfgfile/schema.go
- context/context.go
The actual configuration happens in the `default-snippet`. The Sidecar checks that the PID file directory exist and in doubt creates it. This needs to be configurable in case the `PidFile` option in the `default-snippet` is changed by the user, e.g. to run the sidecar as non-root user.
Fixes #58
> Make run directory configurable

- glide.lock
Upgrade `github.com/kardianos/service` to current version with [my fix](https://github.com/kardianos/service/pull/79) for the [SysV init script bug](https://github.com/kardianos/service/issues/78). This fixes `collector-sidecar` issue #92. The tests passed for me locally and I'm currently using an RPM built with these changes with no issues.
See a full list of changes between the two versions [here](https://github.com/kardianos/service/compare/2954cfdd7b0c8ab45ef2aa22a44b5f086201836f...6a55aece86cb1cf31706b300854a30d89af9682f).
> Upgrade service version

- dist/recipe.rb
- dist/recipe32.rb
I noticed this when building on OSX. Without these additional configs, RPM/DEBs were built for darwin, resulting in `package collector-sidecar-0.0.9_cb1-1.x86_64 is intended for a darwin operating system` when installing the resulting RPM on Linux.
This change results in `fpm-cook` passing `--rpm-os linux` to `fpm`, see https://github.com/jordansissel/fpm/wiki:
```
--rpm-os OS                   (rpm only) The operating system to target this rpm for. You want to set this to 'linux' if you are using fpm on OS X, for example
```
Which results in `"--target","x86_64-unknown-linux"` being passed to rpmbuild, as well as the additional logging:
```
===> [FPM] Building target platforms: x86_64-unknown-linux {}
```
The ability to pass fpm attributes in fpm-cookery was added …
> Specify linux fpm platform so packages are always created properly

- dist/recipe.nsi
32 and 64 bit executables are now packaged inside a single Windows installer called _X86 - but only the right one will be copied at runtime.
Also, the build number is now obtained from the Makefile (which in turn gets it from github).
> Unified Windows installer + passing the version number to nsis phase

- dist/Common.nsh
- dist/recipe.nsi
I've also added RequestExecutionLevel = admin. For the reason of using "Shared Functions between install and uninstall", see http://nsis.sourceforge.net/Sharing_functions_between_Installer_and_Uninstaller
> Added CheckAdmin and CheckConcurrent functions

- glide.lock
Updates the `service` library to the most recent which adds support for loading environment variables from an optional file in the collector-sidecar init scripts. I personally use these to set configuration variables in the collector-sidecar and filebeat configs, e.g.:
*  `/etc/sysconfig/collector-sidecar`:
```
export NODE_ID=$(hostname)
```
*  `/etc/graylog/collector-sidecar/collector_sidecar.yml`:
```
node_id: ${NODE_ID:no_hostname_variable_set}
```
*  `/etc/graylog/collector-sidecar/generated/filebeat.yml`:
```
fields:
node_id: ${NODE_ID}
```
This is the only new change.
See https://github.com/kardianos/service/pull/80
> Update version of service library to add sourcing variables on startup

- daemon/distributor.go
- daemon/exec_runner.go
- daemon/runner.go
- daemon/svc_runner_windows.go
- glide.lock
- services/periodicals.go
This should fix blocked collector processes during shutdown. Tests to consider:
* Configuration update should restart a collector without creating an event for the supervisor
* Killing a collector process should  be detected and restarted
* After 3 retries the supervisor should stop trying
* Shutdown of the Sidecar should not (rarely) create an supervisor event
* Shutdown should happen pretty much in time
* Beats 5.0.1 should be used for testing
> general cleanup and fix of supervisor race conditions

- daemon/distributor.go
- daemon/exec_runner.go
- daemon/runner.go
- daemon/svc_runner_windows.go
- services/periodicals.go
This changes the Runner interface to only implement a Restart and Shutdown function. Using separate Start and Stop functions is prone to race conditions and would need complicated locking to avoid starting duplicate processes.
> Fix race conditions in start/stop/restart code for the exec runner

- Makefile
- backends/beats/configuration.go
- backends/beats/filebeat/configuration.go
- backends/beats/filebeat/render.go
- backends/beats/filebeat/render_test.go
- backends/beats/winlogbeat/configuration.go
- backends/beats/winlogbeat/render.go
- backends/beats/winlogbeat/render_test.go
- backends/nxlog/configuration.go
- cfgfile/schema.go
- daemon/distributor.go
- daemon/exec_runner.go
- daemon/runner.go
- daemon/svc_runner_windows.go
- services/periodicals.go
In order to solve #116 this PR is fixing the beats.Equal() function. Before comparing two configurations the migratons need to run. Otherwise two different versions of a Beat configuraton are compared and never match. The result is a restart loop. Tests are included.
While fixing this, shortcomings in the exec driver on Windows appeared. They are also part of the problem in #116. The cmd.Wait() function behaves slightly different on Linux and Windows what lead to additional restarts of a collector process during a configuration change. To work around this I am now using low-level atomic.Values for go routine synchronization. The problem is that we need to wait for a process to end in the supervisor (unexpected end) and also in the Restart() function to ensure the process is clearly …
> Fix issue#116 and minor cleanups

- README.md
File /var/spool/collector-sidecar/nxlog does not exist until collector-sidecar service is installed.
> Changed order of operations

- dist/IfKeyExists.nsh
- dist/ReplaceInFile.nsh
- dist/recipe.nsi
Main issue was that the installer was not rendering the configuration template anymore. This was caused by a regression in the ReplaceInFile macro. While working on that I also fixed an issue that prevent an upgrade of the package. The installer tries to replace the binary but this is locked when the service is setup and running.
> Fix Windows installer

- Makefile
- backends/beats/configuration.go
- dist/fetch_collectors.sh
This adds Beats 5.5 support. Configuration changes are based on the release notes: https://www.elastic.co/guide/en/beats/libbeat/5.5/release-notes-5.5.0.html
Additionally a small fix in the Makefile is done to respect other GOPATHs than HOME/.go
> Beats 5.5 support

- Makefile
Glide 0.10.2 (compiled with Go 1.6) fails on macOS High Sierra 10.13.2 (17C205).
Seems to be related to golang/go#17182.
Kernel version:
```
$ uname -v
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
```
Error with Glide 0.10.2:
```
$ ./glide install
failed MSpanList_Insert 0x9b8000 0x2ee76050da1e0 0x0 0x0
fatal error: MSpanList_Insert
runtime stack:
runtime.throw(0x640ae0, 0x10)
/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbfeb60 sp=0x7ffeefbfeb48
runtime.(*mSpanList).insert(0x89b588, 0x9b8000)
/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbfeb90 sp=0x7ffeefbfeb60
runtime.(*mheap).freeSpanLocked(0x89ad80, 0x9b8000, 0x100, 0x0) …
```
> Upgrade to Glide 0.13.1

- main.go
In order to programmatically use the `-configtest` command and handle any other error with regard to configuration parsing, Collector Sidecar should exit with an exit code != 0 to indicate an error.
Fixes #220
> Exit with return code 1 if config parsing failed

- README.md
- collector_sidecar_windows.yml
- dist/recipe.nsi
Like requested from a couple of users this PR adds more switches to the Windows installer.
In silent mode it's now possible to set these:
```
-SERVERURL
-TAGS
-NODEID
-UPDATE_INTERVAL
-TLS_SKIP_VERIFY
-SEND_STATUS
-NXLOG_ENABLED
-FILEBEAT_ENABLED
-WINLOGBEAT_ENABLED
```
The interactive installer can set the following options:
```
-SERVERURL
-TAGS
-NODEID
```
Closes #176 
Replaces #198
> Add more installer switches

- README.md
Updated markdown in the README file to fix the Windows Installer Options table
> Fix Windows Installer options table in README file.

- backends/beats/filebeat/render.go
- backends/beats/winlogbeat/render.go
In order to use snippets as main configuration container the Sidecar should not render an empty prospector. This prevents user defined inputs in snippets.
Fixes #208
> Render prospector only if inputs are available

- api/graylog.go
- backends/status.go
- daemon/daemon.go
- daemon/exec_runner.go
- daemon/runner.go
- services/periodicals.go
Fixes #238 
##Explanation
We store a 1:1 copy of the available collectors of the Graylog server in the structure called `backends.Store`. When a configuration is assigned to a Sidecar a new `Runner` instance is created with a _copy_ of the responding `Backend`. Now we have to make sure that status changes (as well as configuration changes/compares) are made to that copied `Backend` and not to the original list of backends. We need that copy to allow multiple instances of the same collector type.
> Cleanup backend access

- backends/backend.go
Fixes #239 
Should the value for the timeout be configurable, it's set to 30s currently.
> Add timeout for validation command

- api/graylog.go
- api/graylog/requests.go
The collector backend status data structure changed from a map to a set
of objects.
Refs Graylog2/graylog2-server#4885
Refs Graylog2/graylog2-server#4886
> Adjust status request to changes in the server

- context/context.go
- dist/recipe.rb
- dist/recipe32.rb
- sidecar-example.yml
This brings the sidecar in line with the graylog-server package which
stores data in "/var/{log,lib}/graylog-server".
> Change default paths to avoid another subdirectory

- dist/recipe.rb
- dist/recipe32.rb
This avoids conflicts with the official filebeat DEB/RPM packages which also install into `/usr/bin`.
Fixes #211
> Install filebeat into /usr/lib/graylog-sidecar/filebeat

- api/graylog.go
Fixes https://github.com/Graylog2/graylog2-server/issues/4899
> Limit list_log_file response size

- api/graylog/responses.go
- backends/backend.go
- backends/registry.go
- common/helper.go
- daemon/exec_runner.go
- daemon/svc_runner_windows.go
- glide.lock
- glide.yaml
After https://github.com/Graylog2/graylog2-server/issues/4889 is fixed the arguments list is stored as single string so we need to split it up.
> Use shlex to split command argument list

- daemon/action_handler.go
- daemon/exec_runner.go
- daemon/svc_runner_windows.go
Removes duplicate log lines and prevent unnecessary stop action if the collector is not running.
> Cleanup action handling

- api/graylog.go
- services/periodicals.go
The overall sidecar status is cleaned up with this change. It provides a summary of all registered collectors in the form `1 running / 0 stopped / 1 failing` e.g. If one or more collectors are in a non-running state the Sidecar also reflects this by changing its state. The overall status can be overwritten in case something fundamentally went wrong, e.g. a template server error. An error message is shown in that case in the web UI as long as the Sidecar is still able to report it back to the server.
> Make overall Sidecar status more explicit

- backends/backend.go
- common/exec_helper.go
- common/exec_helper_windows.go
On Windows, commandline parameters are actually passed as one long
string. (They are then parsed the program itself).
Go however, only provides the exec.Command() API, which needs the
arguments split up. (And will later join them again ...)
Import the CommandLineToArgv() version of Go's os/exec_windows
and use it to split Windows commandlines.
Fixes #290
> Add special commandline parsing for Windows

- backends/beats/filebeat/render.go
- backends/beats/winlogbeat/render.go
- dist/fetch_collectors.sh
Our bundled filebeat had a memory leak (elastic/beats#6797).
Fixes #283
While here:
The "-configtest" option is deprecated since Beats 6.0.
Add a version switch to avoid warning.
> Update filebeat and winlogbeat to 6.4.1

- Makefile
previously it only printed the string "Makefile" instead of the possible target names
since we don't care about the file name, we make grep not print it, so awk finds the proper target names to print
turns
```
13:28 $ make help
Makefile                       Build sidecar binary for local target system
Makefile                       Build sidecar binary for OSX
Makefile                       Build sidecar binary for Linux 32bit
Makefile                       Build sidecar binary for Linux
Makefile                       Build sidecar binary for Solaris/OmniOS/Illumos
Makefile                       Build sidecar binary for Windows 32bit
Makefile                       Build sidecar binary for Windows
Makefile                       Remove binaries
Makefile                       Run gofmt …
```
> fix help Makefile target

- context/context.go
Also try to create the directory right away.
It's easier to debug if we fail early.
Fixes #309
> Fail startup if collector configuration dir is not absolute

- backends/backend.go
- services/periodicals.go
Change the ValidateConfigurationFile function to return errors instead of a boolean.
This allows for more specific error messages in the user interface.
Fixes #311
> Improve collector validation error messages

- daemon/daemon.go
- daemon/exec_runner.go
- daemon/svc_helper.go
- daemon/svc_helper_windows.go
- daemon/svc_runner_windows.go
- glide.lock
- services/control_handler_windows.go
This change addresses several issues how we handle windows
services:
- Change the DisplayName of the Sidecar itself so it does not conflict
with old sidecars.
- If a sidecar backend (aka collector) gets renamed, update the
DisplayName to avoid a conflict with the existing service.
- If backends get renamed, or deleted while the sidecar isn't running
there was no way we could cleanup those.
Therefore update golang/x/sys to a newer version that supports
`ListServices()` so we can search for stale registered services
and clean those.
- Improve error handling in `ValidateBeforeStart()` which could
lead to a panic if a service could not be created.
Fixes #319
> Fix and improve Windows service handling

- daemon/daemon.go
- daemon/exec_runner.go
If the service type changes, switch the backend to a new runner.
> Handle backend changes

- daemon/daemon.go
Avoid calling a nil function in the runnerRegistry.
This error is not reported to the UI.
We do have validations that should prevent this from being configured.
So this is more like a second safety net.
> Fix sidecar crash when using "svc" runner under linux

- cfgfile/cfgfile.go
- cfgfile/schema.go
- context/context.go
- sidecar-example.yml
- sidecar-windows-example.yml
Don't use `ucfg.Merge` because this will merge the contents
of two slices by copying them on top of each other.
Use a much simpler approach and just join the configuration
strings together before parsing them.
Fixes #327
> Fix configuration parsing of lists

- cfgfile/cfgfile.go
According to the yaml spec, the seperator can have
"a line break or a sequence of space characters"
Fixes #327
> Improve yaml doc seperator match

- api/graylog.go
- api/graylog/responses.go
- services/periodicals.go
The response to the registration PUT request contains
configuration assignments, which can be cached as well.
Only run the assignment updates if either the backends or the
assignments have changed.
While here, replace `IsEmpty()` with an `NotModified` flag on each
response struct.
> Add Etag caching for UpdateRegistration results

- api/rest/rest.go
In case we don't process the entire response, discard the remaining
body. This allows the http client to reuse an existing connection,
without having to setup a new one. This is even more expensive when
TLS is used. cf https://github.com/google/go-github/pull/317/files
> Ensure we can reuse a connection

- api/rest/rest.go
- benchmarks/bench-rest-api.go
- Incorporate changes to build this against the new sidecar.
- We now need to fetch assigned configurations. Do this in the heartbeat
loop.
- Add simple request time metrics
- Add -iterations flag, so the that the benchmark terminates
voluntarily and allows for reproducability.
> Fix and update API benchmark

- api/rest/rest.go
In case we don't process the entire response, discard the remaining
body. This allows the http client to reuse an existing connection,
without having to setup a new one. This is even more expensive when
TLS is used. cf https://github.com/google/go-github/pull/317/files
(cherry picked from commit 8a6dadc44238c5a7496453eb6d407daa3ef0f057)
> Ensure we can reuse a connection (#337)

- README.md
Remove alpha version warning and strip down the readme
to a minimum, so we don't have to maintain two versions.
> Update Readme to 1.0

- dist/recipe.nsi
Removed the lines to default the node name to graylog-sidecar. 
The current action doesn't match the documentation.
" The node name of the sidecar. If this is empty, the sidecar will use the hostname of the host it is running on." When installing the setup defaults to graylog-sidecar
> Stop setting default node name to graylog-sidecar

- dist/recipe.nsi
It's a better default to use the system's hostname.
Fixes #339
> Default the windows installer to an empty nodename

- assignments/assignment.go
- daemon/daemon.go
- services/periodicals.go
If an assignemnt is changed to switch a backend from
one configuration to another, we would still send configuration requests
using the old checksum.
The server will respond with `NotModified` and we don't try to restart
the backend.
Instead of also resetting the checksum when we update the assignment
store, simply wipe the entire checksum map if either the assignment
or the backends have changed.
Fixes #352
> Wipe configchecksums also on assignment changes

- Makefile
- dist/recipearmv7.rb
This way it's more specific.
Refs #355 #271
> Change armhf name to linux-armv7

- glide.lock
- glide.yaml
It is broken and not used anymore
(cherry picked from commit e13dbd82571088c301eef38cc4654c145121e255)
> Remove unused strftime dependency

- dist/fetch_collectors.sh
Beats <= 6.4.x is EOL since February.
Releasing this should probably coordinated with a backport of this change: https://github.com/Graylog2/graylog2-server/pull/7879
> Update filebeat and winlogbeat to 7.6.2

- Makefile
- dist/fetch_collectors.sh
- Make sure we ship the OSS version
- Add prepare-package as a dependency for package-windows
(cherry picked from commit ff73bb991e38ca0d4b6115f3cc72767b106ef4bb)
> Update beats to 7.11.1  (backport to 1.1)

- dist/recipe.nsi
Update the Windows installer to create a `module` directory for Winlogbeat. 
Fixes #412
> Update Windows installer to create module directory.

- Makefile
- dist/tools.rb
- go.mod
- go.sum
- jenkins.groovy
Fixes an issue where starting sidecar on FreeBSD would fail with the following error:
```
FATA[0000] Operating system is not supported: No service system detected.
```
The issue was caused by the `github.com/kardianos/service` dependency, which doesn't provide support for FreeBSD in the previously used version. 
Updating it to `v1.2.1` fixes the issue.
> Fix startup issue on FreeBSD

- main.go
- services/service_options.go
- services/service_options_windows.go
After a reboot, this will delay service startup a little.
Also, if the service fails after initially running, it will now be restarted after a delay of two minutes.
The goal of this change is to reduce the chance of sporadic startup issues on Windows, that some users have been experiencing.
Resolves #421
> Set Windows service type to "Automatic (Delayed Start)"

- common/fs.go
- common/helper.go
- common/helper_test.go
The test if a directory exists is currently broken on Windows. This leads to the sidecar not creating the parent directory for the configured node-id file if the directory doesn't exist yet.
This PR fixes that by using `filepath.Dir` instead of `path.Dir`.
Additionally, logging is improved by adding logging for unsuccessful attempts to write to the node-id file.
> Fix directory existence test on Windows

- .gitignore
- Makefile
> Add Mac M1 sidecar build

- api/graylog.go
When the configuration fetch request failed without an HTTP status code, the sidecar would treat this as a config change and clear its current configuration.
With this change, the failed request won't lead to the invalidation of the current configuration anymore.
Fixes #413 
Reproducing this is a bit tricky because the behaviour can only be triggered when the request to `/api/sidecar/collectors` succeeds, but the subsequent request to `/api/sidecar/configurations/render/*` fails. 
I used [caddy](https://caddyserver.com/) as a proxy server between the sidecar and the Graylog server to selectively let the latter call fail. This is the `Caddyfile` I was using:
```
{
debug
}
:2016 {
@config_fetch {
path /api/sidecar/configurations/render/*
expression (int({time.now.unix}) % 20) < 10
}
handle …
```
> Don't clear configuration when the fetch request fails

- backends/backend.go
- cfgfile/schema.go
- context/context.go
- sidecar-example.yml
- sidecar-windows-example.yml
Intoduce a new config option: `collector_validation_timeout = 1m`
Also increase the default timeout from 30s to 1m
since 30s seems to low for some use cases.
Fixes #431
> Make validation timeout configurable

- backends/backend.go
- cfgfile/schema.go
- context/context.go
- sidecar-example.yml
- sidecar-windows-example.yml
Intoduce a new config option: `collector_validation_timeout = 1m`
Also increase the default timeout from 30s to 1m
since 30s seems to low for some use cases.
Fixes #431
(cherry picked from commit 56bd1531a6655ed3d783fa38be8b6ecc30a65011)
> Make validation timeout configurable (#435)

- api/graylog.go
Fixes #439 
Correctly calculate the combined status for a sidecar by using the worst status of any collector. This was probably the original intention, but the used switch statement was handling the "stopped" case wrong.
> Fix combined status

- api/graylog.go
- api/graylog/requests.go
- cfgfile/schema.go
- sidecar-example.yml
Adds a configuration option to assign tags to a sidecar.
Tags configured in `sidecar.yml` are sent to the server where they can be used to apply matching configuration automatically. This PR just adds support to configure and send the tags attribute. The heavy lifting will be done on the server.
> Add "tags" field to configuration and registration request

- Makefile
- dist/chocolatey/gensha.sh
- dist/chocolatey/graylog-sidecar.nuspec
- dist/chocolatey/tools/.gitignore
- dist/chocolatey/tools/chocolateyinstall.ps1.template
- docker/Dockerfile.chocolatey
- jenkins.groovy
The build now creates a Chocolatey .nupkg file on every build and
publishes the file when building a release.
Refactor the pipeline script to run all stages on the same node. This
ensures that all stages have access to the build artifacts and we don't
have to stash/unstash the files for each stage.
Additional changes:
- Update "graylog-sidecar.nuspec" file with latest URLs and author
information
- Generate the "chocolateyinstall.ps1" file from a template for every
build instead of overwriting the file for each release.
- Apply consistent formatting for the pipeline script
> Implement Chocolatey build and refactor pipeline script

- api/version.go
How did I miss this? :roll_eyes:
> Fix version check for Graylog 5 and beyond

- api/graylog.go
> Only log the disablement of send_status once

- dist/recipe.nsi
- sidecar-windows-example.yml
The installer can now also upgrade existing sidcar installations.
It detects this by the presence of an existing sidecar.yml config.
In upgrade mode it skip the configuration page.
Additionally the installer will now also register the sidecar
service automatically. Making this extra command line step obsolete.
For debugging purposes, we write a installerlog.txt file now.
Improve welcome message test to also show the version and mention the
autmatic upgrade mode.
Only replace the winlogbeat and filebeat collector binaries AFTER
we stopped the sidecar. Otherwise the files might still be locked
and the upgrade fails.
Suppport `-NODEID param` for silent installer
Also fix default node-id file location for 32-bit installs
Fixes #365 
Fixes #432
> Add upgrade support and improve windows installer

- api/graylog.go
- assignments/assignment.go
- backends/backend.go
- backends/registry.go
- backends/render.go
- cfgfile/schema.go
- changelog/unreleased/issue-463-bis.toml
- changelog/unreleased/issue-463-quater.toml
- changelog/unreleased/issue-463-ter.toml
- changelog/unreleased/issue-463.toml
- context/context.go
- daemon/action_handler.go
- daemon/daemon.go
- daemon/distributor.go
- daemon/exec_helper.go
- daemon/exec_helper_windows.go
- daemon/exec_runner.go
- helpers/argv_helper.go
- helpers/argv_helper_windows.go
- helpers/helper.go
- helpers/helper_test.go
- logger/hooks/hooks.go
- main.go
- sidecar-example.yml
There are scenarios in which the sidecar handles stopping / restarting it's forked collectors poorly:
1. The collector is a wrapper script that forks additional processes
2. The wrapper script runs the collector with elevated privileges (sudo)
This PR tries to improve handling this as much as possible.
Instead of killing just the forked PID, it also resorts to killing the entire process group.
This should cover case `1`
For case `2` the sidecar can only avoid waiting forever on a process it is not allowed to kill. (lack of permissions)
This is fixed by adjusting the timeout loop and introducing a terminate channel to abort the goroutine that is endlessly wait(2)ing.
The timeout between sending a `SIGTERM` and  `SIGKILL` can be adjusted with a new configration option: …
> Improve process shutdown handling

- changelog/unreleased/issue-364.toml
- dist/go.mod
- helpers/helper.go
Both usually have case-insensitive file systems.
Feels like this should be fixed in go instead:
https://github.com/golang/go/issues/5441
Also remove a stray go.mod file, that causes IJ to throw a warning on startup.
Fixes #364
> Match collector_binaries_accesslist case insensitive on windows and MacOS

- cfgfile/schema.go
- changelog/unreleased/pr-472.toml
- dist/fetch_collectors.sh
- dist/recipe.nsi
- dist/recipe.rb
- dist/recipe32.rb
- sidecar-example.yml
- ship Logbeat with Linux x64 & x86
- ship Audit with Linux x64 & x86
- ship sidecar with `default` tag in sidecar.yml
part of Graylog2/graylog2-server#15570
> Ready-to-use sidecar configurations

- api/graylog.go
- api/rest/rest.go
- changelog/unreleased/issue-481.toml
- services/periodicals.go
If we fail to read the server version from Graylog, stop using a fallback to 4.0.0 and retry the request instead.
In scenarios with multiple Graylog nodes behind a load balancer, this can lead to the sidecar temporarly stopping all collectors.
Fixes #481
> Abort request on missing Graylog server version

- changelog/issue-479.toml
- services/periodicals.go
We are using HTTP keep-alive, which might never pick up any changes to the DNS name of Graylog.
Since there is no parameter in golang's http.Client to do this, simply re-create a new HTTP connection every 60 calls.
Fixes #479
> Re-create HTTP connection to Graylog 60 update iterations

- Makefile
- api/version.go
- changelog/unreleased/pr-480.toml
- common/sigar.go
- common/sigar_solaris.go
- daemon/svc_helper.go
- dist/fetch_collectors.sh
- dist/recipearm64.rb
- services/control_handler_unix.go
> Add ARM64 binary and package builds
