- dist/recipe.nsi
it needs the graylog.ico file in the /dist folder
> Add Graylog icon and Windows uninstaller entry for 64 bit

- dist/recipe32.nsi
it needs the graylog.ico file in the /dist folder
> Added Graylog icon and Windows uninstall link for 32 bit

- Makefile
Sorry, this is to be merged with PR #101
> Unified Windows installer + passing the version number to nsis phase

- api/graylog.go
- api/rest/rest.go
- backends/beats/filebeat/filebeat.go
- backends/beats/winlogbeat/winlogbeat.go
- backends/nxlog/nxlog.go
- backends/registry.go
- cfgfile/cfgfile.go
- common/fs.go
- common/helper.go
- context/context.go
- daemon/daemon.go
- daemon/exec_runner.go
- glide.lock
- glide.yaml
- logger/hooks/hooks.go
- logger/logger.go
- main.go
- services/periodicals.go
Cleanup logging so that Sidecar logs and backend logs are in one drectory for better debugging.
> Replace syslog with rotated file logger

- main.go
Allow to set log level with `-debug`
> Add debug switch

- dist/recipe.nsi
With standard pages and header messages. Also, the GNU license must be accepted.
> Using Modern UI in a standard way

- Makefile
- dist/fetch_collectors.sh
- dist/recipe.nsi
* Update to Beats 5.1.1  
* Remove collector binaries on make clean
* Create missing log directory on Windows
> Update to Beats 5.1.1 and cleanups

- glide.lock
- glide.yaml
In order to debug #128 let's keep focused on stable Logrus releases.
> Pin to stable Logrus version

- Makefile
- services/control_handler_unix.go
Adding the option to build the sidecar for FreeBSD. Did not add it to the default make task on purpose.
> Adding build task and target for FreeBSD.

- Makefile
- dist/recipe32.rb
Include version.mk for i386 and tar-ball packages.
> Fix packaging

- daemon/svc_runner_windows.go
In order to fix the same race conditions we fixed in the exec_runner this PR:
* adds the signalProcessor to the svc_runner to serialize concurrent restart requests
* make use of atomic state variables
* starts a single supervisor per instance
Fixes #142 
Can be tested by activating nxlog as backend and reboot the machine. The state of the collector should be green in the web interface afterwards.
> Fix race conditions

- backends/beats/filebeat/render.go
- backends/beats/winlogbeat/render.go
- backends/nxlog/render.go
- context/context.go
See https://github.com/Graylog2/collector-sidecar/pull/155
> Add NodeID to context so that it may be shipped

- common/sigar.go
> Close file hanle after searching for system drives. Fixes #146

- backends/beats/configuration.go
- backends/beats/filebeat/filebeat.go
- backends/beats/winlogbeat/winlogbeat.go
- dist/fetch_collectors.sh
> Update to Beats 6.1.2

- collector_sidecar.yml
> Remove node_id from default configuration and fallback to hostname

- daemon/svc_runner_windows.go
Fixes #238 for Windows SVC runner.
> Adopt svc_runner to pr-244

- context/context.go
- main.go
> Expose YAML parse error to command line

- dist/recipe.nsi
> Set product version in installer binary

- context/context.go
> Check if an empty string is configured as node-id

- common/sigar.go
Quick-fix for #230 till we switch to something like gops.
> Exclude floppy drives

- backends/backend.go
> Make validation command optional

- api/rest/rest.go
Relates to https://github.com/Graylog2/graylog2-server/pull/4987
> Add X-Requested-By header

- backends/backend.go
- cfgfile/schema.go
- common/helper.go
- context/context.go
- daemon/exec_runner.go
- daemon/svc_runner_windows.go
- services/periodicals.go
- sidecar-example.yml
- sidecar-windows-example.yml
> Add binary whitelist feature

- backends/status.go
- daemon/exec_runner.go
- daemon/svc_runner_windows.go
Fixes #254 
Depends on https://github.com/Graylog2/graylog2-server/pull/5017
> Add stopped state

- backends/backend.go
- backends/render.go
- daemon/exec_runner.go
- daemon/svc_runner_windows.go
- services/periodicals.go
> Fix missing whitelist check

- dist/recipe.rb
- dist/recipe32.rb
- sidecar-windows-example.yml
Fixes #289
Fixes Graylog2/graylog2-server/#4887
> Fix more default paths

- README.md
- dist/recipe.nsi
- sidecar-windows-example.yml
> Have the Windows installer ask for the API token

- .travis.yml
- cfgfile/schema.go
- context/context.go
- daemon/exec_runner.go
- glide.lock
- glide.yaml
- logger/hooks/hooks.go
- logger/logger.go
- sidecar-example.yml
- sidecar-windows-example.yml
Use size based log rotation, which can be configured in megabytes and days
Fixes #251
> Switch to a more user friendly log rotation configuration

- backends/backend.go
- cfgfile/cfgfile.go
- cfgfile/schema.go
- context/context.go
- glide.lock
- glide.yaml
- sidecar-example.yml
- sidecar-windows-example.yml
The user should only have to worry about a minimum of settings.
Update ucfg dependency to the new repository.
> Add builtin sidecar configuration defaults

- api/graylog.go
(cherry picked from commit c39a22661fb541645b31a0ecbcc807624f2b33a9)
> Only fetch metrics if we are gonna send them (#336)

- Makefile
> Include example configurations in tar-ball

- Makefile
- dist/recipearm.rb
I added an option to automatically build armhf binary and package.
> Added build option for armhf

- glide.lock
- glide.yaml
It is broken and not used anymore
> Remove unused strftime dependency

- CONTRIBUTING.md
> Update contributing url

- Makefile
- dist/fetch_collectors.sh
- Make sure we ship the OSS version
- Add prepare-package as a dependency for package-windows
Fixes #404
> Update beats to 7.11.1

- backends/backend.go
- backends/registry.go
- daemon/action_handler.go
An action is retrieved per collector ID.
We need to iterate over all backends for a collector and execute that action.
> Handle action requests for collectors

- changelog/unreleased/issue-431.toml
- changelog/unreleased/pr-428.toml
- changelog/unreleased/pr-441.toml
- changelog/unreleased/pr-441bis.toml
- changelog/unreleased/pr-447.toml
Let's collect all 5.0 changelog snippets in this pull request.
Please add your snippet files to the `changelog/unreleased` folder
as described in our internal documentation.
Thank you!
> Add 5.0 Changelogs

- Makefile
- dist/chocolatey/gensha.sh
- docker/Dockerfile.chocolatey
- jenkins.groovy
- Sign all Windows binaries
- Automate GitHub release creation and asset upload
> Release build improvements

- .github/workflows/changelog.yml
Checks the presence of changelog snippets.
/nocl
> Add changelog workflow

- dist/fetch_collectors.sh
- go.mod
- go.sum
- jenkins.groovy
> Update golang to 1.21 and some dependencies

- dist/fetch_collectors.sh
> fix auditbeat collector version
